### ISSUE TITLE
duplicate functions in compiled codebase

### ISSUE THREAD

**Issue by vlandham** [moebiolabs/moebio_framework#172]
in `moebio_framework.js` the functions in `NumberTableOperators` appear to be duplicated. One in the object: 

```
numberTable_NumberTableOperators__NumberTableOperators
```

and one in:

```
NumberTableOperators__NumberTableOperators
```

`NumberTableOperators` is only imported (from what I can tell) in one additional file:

```
ObjectOperators.js
```

If this import is removed, then the duplicated functions go away.

**Comment by tafsiri** [comment]
I think this has been fixed in #173
