### ISSUE TITLE
Remove sensitive/old data

### ISSUE THREAD

**Issue by tafsiri** [moebiolabs/moebio_framework#174]
Is there any sensitive or old data we should remove from the framework?

- Client info/names
- Keys
- Old code

Please post things to this issue.

@vlandham @moebio @Jeff-Clark @tafsiri

**Comment by Jeff-Clark** [comment]
The files still in the framework resources folder are all .csv or .json. They may be used by some existing projects but do not belong with the framework. We do need a place in the **modular_platform** repo for sample/example data and perhaps these should be moved there.

**Comment by vlandham** [comment]
ok. @moebio would that make sense? move `resources` to Modular platform for now?

**Comment by moebio** [comment]
Modular already has a resources folder (ignored by git). Files placed there are for projects.

resources folder in frameworks is for somehow universal data that could be useful in multiple projects. It has got frequencies tables of words in english (useful for syntactic analysis), geo coordinates for country borders and usa states, and coordinates for a parametrized font that I used on some projects and might be as well used in others. 

So I think those files are well placed on the framework, at least for the time being.

**Comment by Jeff-Clark** [comment]
I'm happy to have them remain in frameworks but it does seem like an odd location to me for data files - even if 'universal'. Pretty much any geographic data could be considered 'universal data' (well 'planetary' anyways) so should we group any future geographic data files with the framework? The current resources folder only has a few files but it is already about 3x bigger than the src directory in terms of MB.

I'm not sure but I don't believe any of the data files are referenced within the framework code itself.

**Comment by moebio** [comment]
Yeah you're right. In the future we'll have a data place, in a more complex ecosystem with lichen, the store, edn, etc… 

Do you think is a good idea to actually place those files as accesible data files in github? as another asset in github.com/moebiolabs?

**Comment by vlandham** [comment]
we could easily have a public repo `moebio_resources` - to collect such things - if you felt they were worth sharing with the community.

**Comment by protozoo** [comment]
+1 to have it in a separate repo.

**Comment by moebio** [comment]
+1 (yes, and now that it's a thing, we would be prone to add more generally relevant data files)

**Comment by protozoo** [comment]
Ok, I've done some searching and didn't find any passwords, api keys or similarly sensitive data. Just a few minor (I think) things to consider:


- src/tools/loaders/Loader.js
	- 8: *//TODO:install proxy created by Mig at moebio.com*
	- 59: *//if (req.status == 200) { //MIG*
- libraries folder
	- Is it OK to include these within our own project? No license problems? Maybe better to reference it as npm dependencies?
- vendor/loader.js
	- Same question as previous item

**Comment by Jeff-Clark** [comment]
+1 agree with separate repo. I presume for consistency it gets placed at the same level as the other repos. It's location wrt lichen should be well-defined so code knows where to access things. At some point in the future it might be useful to have some Lichen configuration option that makes it easy to change the URL base for your `moebio_resources`

**Comment by tafsiri** [comment]
@protozoo For vendor/loader.js we are okay. It is MIT licensed. For the other files in ```libraries``` we would want to check their licenses. 

However I am also not sure they are currently loaded by the framework, so i'm not sure if the user is expected to load them themselves. If so maybe they shouldn't be in the repo itself. But I'm honestly not too sure how they are used.

**Comment by Jeff-Clark** [comment]
Alea.js and Mash.js were incorporated directly into the framework inside NumberOperators. There is a comment there with a link ( http://baagoe.org/en/w/index.php/Better_random_numbers_for_javascript ) but the link will not open so I don't know license.

**Comment by vlandham** [comment]
Ah yes. i followed this rabbit hole for another reason related to initial linting work. I found a mirror of these files on github with a MIT license with some notes:
https://github.com/nquinlan/better-random-numbers-for-javascript-mirror/blob/master/LICENSE.md

**Comment by vlandham** [comment]
and as @tafsiri says - i don't think any of these are loaded in. with this PR #171 : https://github.com/moebiolabs/moebio_framework/pull/171/commits 

I plan to remove the directory. It is already in our legacy repo in case we need it.
