### ISSUE TITLE
Examples links are broken in Safari

### ISSUE THREAD

**Issue by darthmall** [moebiolabs/moebio_framework#203]
All of the example links take me to the Cube example regardless of what comes after the # in the URL. Could be a Safari bug, but maybe there's an easy workaround.

I'm on Safari 8.0.8.

**Comment by vlandham** [comment]
thanks very much! i will figure this out and get it fixed!

**Comment by vlandham** [comment]
this should now be fixed on the website (which is managed on its own private repo right now - so there isn't a commit to associate with this issue here)

http://moebiolabs.github.io/moebio_framework/

**Comment by darthmall** [comment]
Nice work. Thanks.
