### ISSUE TITLE
Exception calling Matrix.translate

### ISSUE THREAD

**Issue by darthmall** [moebiolabs/moebio_framework#215]
I get an exception when I call the `translate` method on a `Matrix` object: "TypeError: Matrix.translation is not a function".

#### Example
```javascript
var m = new mo.Matrix();
m = m.translate(1, 1);
```

The exception occurs on [line 139 of Matrix.js](https://github.com/moebiolabs/moebio_framework/blob/f41c9d5501439c661326f9fbb03cb28edabfa8f1/src/dataTypes/numeric/Matrix.js#L139).

**Comment by darthmall** [comment]
I'm getting a similar error calling `scale` on a Matrix: "Matrix.scale is not a function" on [line 126](https://github.com/moebiolabs/moebio_framework/blob/f41c9d5501439c661326f9fbb03cb28edabfa8f1/src/dataTypes/numeric/Matrix.js#L126).

**Comment by Jeff-Clark** [comment]
Addressed by PR https://github.com/moebiolabs/moebio_framework/pull/216 . Thanks @darthmall for finding and fixing the problem!
