### ISSUE TITLE
Method Network.getNodeWithName calls nodeList.getNodeWithName which does not exist

### ISSUE THREAD

**Issue by Jeff-Clark** [moebiolabs/moebio_framework#218]
Method Network.getNodeWithName calls nodeList.getNodeWithName which does not exist.
There is a method nodeList.getNodeByName which is the intended call so there is a name mismatch.

Don't know if you want to change them consistently to getNodeByName or getNodeWithName.

There is the same problem with getNodeWithId/getNodeById.

**Comment by moebio** [comment]
Ok, there's now:

getNodeById and getNodeByName

both in NodeList and Network (and only the ones present in NodeList have tags thus being accesible as modules)

getNodeWithName no longer exists

**Comment by Jeff-Clark** [comment]
This problem seems to be back as it was before. In master branch for fw I see getNodeWithId for network but getNodeById for NodeList

**Comment by moebio** [comment]
@Jeff-Clark  I think I closed the ticket before pushing changes, please check again

**Comment by Jeff-Clark** [comment]
Looks good.
