### ISSUE TITLE
Sort speed, stability, and applicability

### ISSUE THREAD

**Issue by Jeff-Clark** [moebiolabs/moebio_framework#219]
Some changes were made fairly recently to List.prototype.getSortedByList and ListOperators.sortListByNumberList for performance reasons. (Commit https://github.com/moebiolabs/moebio_framework/commit/e3ab959b2ad25aca1d478c1c481438c60ef1a582#diff-2c93a0cb2e3911d717c568f1ab9c59f7)

Basically, the comparators were changed from 
* `return a[1] < b[1] ?  1 : a[1] > b[1] ? -1 : a[2] - b[2];`
to
* `return b[1] - a[1];`

This is indeed faster (almost twice as fast in my tests). Unfortunately it breaks in the case of sorting by strings and is no longer a stable sort. The a[2] - b[2] in the original comparator for equal values preserves the original order. This is important when sorting a table or list by another list.

The 2x speed advantage in the case where we don't care about sort stability is worth keeping for sure.

@moebio 
I propose:
1. we test the list datatype and revert to the old style comparator for stringLists.
2. we add a parm to function for sort stability and use the comparator that provides it in that case. Default for stable sort is off.
3. we change TableOperators.sortListsByNumberList to have it turn on stable sort

How does that sound?

**Comment by moebio** [comment]
Indeed, that's reason the method used comparators in the first place.

@Jeff-Clark I think 1 is the right approach. StringList and DateList (what else?) would use comparator.

**Comment by Jeff-Clark** [comment]
fixed.
