### ISSUE TITLE
improve TableOperators.getFilteredByValue

### ISSUE THREAD

**Issue by moebio** [moebiolabs/moebio_framework#228]
( @Jeff-Clark I'm assuming this module was developed by you)

Two interesting features could be added (I think without too much work):

• In the second inlet, operator, also accept a (boolean) Function
• In the fourth inlet, nList, also accept a list (so the table could be filtered by an external list)

I haven't test it, but it seems to me that when there's no nList value, the method doesn't work for nLKeep is n*m, longer than m (number of rows).

**Comment by Jeff-Clark** [comment]
Those both sound like good ideas. I will check the functionality with nList == null for problems.
