### ISSUE TITLE
There should be an easy way to concatenate all the rows from multiple tables with the same structure

### ISSUE THREAD

**Issue by Jeff-Clark** [moebiolabs/moebio_framework#233]
There should be an easy way to concatenate all the rows from multiple tables with the same structure.

List.concat works for lists but for Table it adds new lists rather than elements to the end of existing list.

We need something like a TableOperators.concatElements which would concat each list in turn.

**Comment by Jeff-Clark** [comment]
Dani said you were going to do this.

**Comment by moebio** [comment]
@Jeff-Clark It would be great if you do it, because I'll do another very much needed operator which is table aggregation by different lists

**Comment by moebio** [comment]
name: concatLists?

**Comment by Jeff-Clark** [comment]
I will do it. I think concatLists would be confused with List.concat. Perhaps concatRows?

**Comment by moebio** [comment]
agree

**Comment by Jeff-Clark** [comment]
Complete. See TableOperators.concatRows
Handles uneven number of cols and uneven col lengths.
Test project: jeff/test/concatRows

@moebio close if happy with it or give feedback.
