### ISSUE TITLE
CSVloader fails to properly load heroes.csv

### ISSUE THREAD

**Issue by Jeff-Clark** [moebiolabs/moebio_framework#238]
see jeff/bug/CSVloader-0

I'm guessing it may be change to handling of quotes in the recent commit https://github.com/moebiolabs/moebio_framework/commit/34c03631e650859d2a0f60ab79b1d6a3005ebf6e

**Comment by moebio** [comment]
tap on this and solve the \n|\r issue 
+ solve this:
#/dani/tests/csvtotableRN

**Comment by moebio** [comment]
seems to be fixed, although I had to withdraw a less important fix regarding the use of ' and "

**Comment by Jeff-Clark** [comment]
yes, works for me now.
